language: php
php:
  - '7.4'

git:
  depth: 1

install:
  # Install composer packages, will also trigger dump-autoload
  - travis_retry composer install --no-interaction
  # - travis_retry composer require codeclimate/php-test-reporter --no-interaction
  # Install coveralls.phar
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version
  
script:
  - ./vendor/bin/phpunit 

after_success:
# Submit coverage report to Coveralls servers, see .coveralls.yml
 - travis_retry php coveralls.phar -v
# Submit coverage report to codecov.io
# - vendor/bin/test-reporter
# - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - mostafabarmshory+eeqna5hwqenxwczq7lax@boards.trello.com
  on_success: never
  on_failure: always
  on_error: always

branches:
  only:
    - master
    - develop
